name: CI

on:
  push:  # This triggers on any commit
    branches:
      - '**'  # Runs on all branches
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # These images are arm64 unless specified: https://github.com/actions/runner-images
        os: [macos-15] # macOS CI is expensive: [macos-14, macos-15, macos-15-intel, macos-26]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Adobe DNG Converter
      run: |
        echo "Downloading the DNG Converter DMG file"
        curl -L -o DNGConverter_17_5.dmg https://download.adobe.com/pub/adobe/dng/mac/DNGConverter_17_5.dmg

        echo "Mounting the DMG file"
        hdiutil attach DNGConverter_17_5.dmg

        # Rosetta2 is installed on arm64 Macs
        if [ -e /Library/Apple/usr/libexec/oah/libRosettaRuntime ]; then
          echo "\nRunning on Apple Silicon"
        else
          echo "\nRunning on Intel"
        fi

        echo "\nInstalling Adobe DNG Converter"
        sudo installer -pkg /Volumes/DNGConverter_17_5/DNGConverter_17_5.pkg -target `pwd`

        echo "\nUnmounting the DMG file"
        hdiutil detach /Volumes/DNGConverter_17_5

    - name: Run reset.sh
      run: |
        chmod +x ./reset.sh
        ./reset.sh

    - name: Run organizeGoProDNG.sh
      run: |
        chmod +x ./organizeGoProDNG.sh
        ./organizeGoProDNG.sh
